// let today=new Date()
// console.log(today)
// console.log(today.getFullYear());
// console.log(today.getDate());
// console.log(today.getMonth());
// console.log(today.getDay());
// console.log(today.getHours());
// console.log(today.getMinutes());
// console.log(today.getSeconds());
// console.log(today.getMilliseconds());
// console.log(today.getTime());
// console.log(Date.now());
// today.setFullYear(2025)
// console.log(today.getFullYear());
// today.setDate(30)
// console.log(today.getDate());
// today.setMonth(5)
// console.log(today.getMonth());
// today.setHours(8)
// console.log(today.getHours());
// today.setMinutes(30)
// console.log(today.getMinutes());
// today.setSeconds(25)
// console.log(today.getSeconds());
// console.log(today.getMilliseconds());
// console.log(today.getTime());